name: "Detekt"
on:
  - push
  - pull_request
jobs:
  detekt:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - uses: natiginfo/action-detekt-all@1.18.0-RC2
